import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

const buttonsClass = `border border-gray-300 rounded px-1 py-0.5 text-white hover:bg-gray-300 hover:text-black`

export default function PostView() {
    const user = useUser()

    return (
        <>
            <Head>
                <title>Demo T3</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="bg-slate-500 p-2 flex justify-between">
                <h2>Demo T3</h2>
                <div>
                    {user.isSignedIn ? <SignOutButton>
                        <button className={buttonsClass}>
                            Sign out
                        </button>
                    </SignOutButton> : <SignInButton>
                            <button className={buttonsClass}>
                                Sign in
                            </button>
                        </SignInButton>}
                </div>
            </header>
            <main>
                <div>
                    Posts
                </div>
            </main>
        </>

    )
}
